### ISSUE TITLE
add documentation

### ISSUE THREAD

**Issue by SilverMiner** [mjtb49/ChunkRandomReversal#3]
Where's like readme file on: how this works (if it has gui, is it cmd stuff and which parameters it's fed with)? Which compilers should one use to build it?

**Comment by mjtb49** [comment]
This repo's main purpose is the ChunkRandomReverser class, which has methods for reversing the various hashes in Minecraft's ChunkRandom class. There is documentation in the form of javadocs on the interesting methods and some example usages in the test cases. It is just a simple java library - you are meant to import it in other java seedfinding code.
